### ISSUE TITLE
Add lost connection handling

### ISSUE THREAD

**Issue by lawrenceleejr** [jslawless/POPSICL#7]
And report to console what's gone wrong, the state of the network connection, etc etc. 

Figure out what the timeout mechanism is for the requests to the DB and when it should retry, etc.

Also have a handling where if you've tried everything and it's been some minutes, reboot the device.

**Comment by Jmgou** [comment]
I've added some connection handling to the main code

**Comment by Jmgou** [comment]
I rewrote the code so that it now only checks connection if posting to the database is unsuccessful.

**Comment by lawrenceleejr** [comment]
Nice. Closing the ticket. Do try to reference commit hashes or PRs in your comments.
